// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SuperStarTrek {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("MainWindow")]
	public partial class MainWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("MainWindowController")]
	public partial class MainWindowController {
		
		private global::MonoMac.AppKit.NSButton __mt_Btn01;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn02;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn03;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn04;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn05;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn06;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn07;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn08;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn09;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn10;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn11;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn12;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn13;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn14;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn15;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn16;
		
		private global::MonoMac.AppKit.NSButton __mt_Btn17;
		
		private global::MonoMac.AppKit.NSTextView __mt_TxtView;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("BtnClicked:")]
		partial void BtnClicked (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Connect("Btn01")]
		private global::MonoMac.AppKit.NSButton Btn01 {
			get {
				this.__mt_Btn01 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn01")));
				return this.__mt_Btn01;
			}
			set {
				this.__mt_Btn01 = value;
				this.SetNativeField("Btn01", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn02")]
		private global::MonoMac.AppKit.NSButton Btn02 {
			get {
				this.__mt_Btn02 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn02")));
				return this.__mt_Btn02;
			}
			set {
				this.__mt_Btn02 = value;
				this.SetNativeField("Btn02", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn03")]
		private global::MonoMac.AppKit.NSButton Btn03 {
			get {
				this.__mt_Btn03 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn03")));
				return this.__mt_Btn03;
			}
			set {
				this.__mt_Btn03 = value;
				this.SetNativeField("Btn03", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn04")]
		private global::MonoMac.AppKit.NSButton Btn04 {
			get {
				this.__mt_Btn04 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn04")));
				return this.__mt_Btn04;
			}
			set {
				this.__mt_Btn04 = value;
				this.SetNativeField("Btn04", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn05")]
		private global::MonoMac.AppKit.NSButton Btn05 {
			get {
				this.__mt_Btn05 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn05")));
				return this.__mt_Btn05;
			}
			set {
				this.__mt_Btn05 = value;
				this.SetNativeField("Btn05", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn06")]
		private global::MonoMac.AppKit.NSButton Btn06 {
			get {
				this.__mt_Btn06 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn06")));
				return this.__mt_Btn06;
			}
			set {
				this.__mt_Btn06 = value;
				this.SetNativeField("Btn06", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn07")]
		private global::MonoMac.AppKit.NSButton Btn07 {
			get {
				this.__mt_Btn07 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn07")));
				return this.__mt_Btn07;
			}
			set {
				this.__mt_Btn07 = value;
				this.SetNativeField("Btn07", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn08")]
		private global::MonoMac.AppKit.NSButton Btn08 {
			get {
				this.__mt_Btn08 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn08")));
				return this.__mt_Btn08;
			}
			set {
				this.__mt_Btn08 = value;
				this.SetNativeField("Btn08", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn09")]
		private global::MonoMac.AppKit.NSButton Btn09 {
			get {
				this.__mt_Btn09 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn09")));
				return this.__mt_Btn09;
			}
			set {
				this.__mt_Btn09 = value;
				this.SetNativeField("Btn09", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn10")]
		private global::MonoMac.AppKit.NSButton Btn10 {
			get {
				this.__mt_Btn10 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn10")));
				return this.__mt_Btn10;
			}
			set {
				this.__mt_Btn10 = value;
				this.SetNativeField("Btn10", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn11")]
		private global::MonoMac.AppKit.NSButton Btn11 {
			get {
				this.__mt_Btn11 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn11")));
				return this.__mt_Btn11;
			}
			set {
				this.__mt_Btn11 = value;
				this.SetNativeField("Btn11", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn12")]
		private global::MonoMac.AppKit.NSButton Btn12 {
			get {
				this.__mt_Btn12 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn12")));
				return this.__mt_Btn12;
			}
			set {
				this.__mt_Btn12 = value;
				this.SetNativeField("Btn12", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn13")]
		private global::MonoMac.AppKit.NSButton Btn13 {
			get {
				this.__mt_Btn13 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn13")));
				return this.__mt_Btn13;
			}
			set {
				this.__mt_Btn13 = value;
				this.SetNativeField("Btn13", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn14")]
		private global::MonoMac.AppKit.NSButton Btn14 {
			get {
				this.__mt_Btn14 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn14")));
				return this.__mt_Btn14;
			}
			set {
				this.__mt_Btn14 = value;
				this.SetNativeField("Btn14", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn15")]
		private global::MonoMac.AppKit.NSButton Btn15 {
			get {
				this.__mt_Btn15 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn15")));
				return this.__mt_Btn15;
			}
			set {
				this.__mt_Btn15 = value;
				this.SetNativeField("Btn15", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn16")]
		private global::MonoMac.AppKit.NSButton Btn16 {
			get {
				this.__mt_Btn16 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn16")));
				return this.__mt_Btn16;
			}
			set {
				this.__mt_Btn16 = value;
				this.SetNativeField("Btn16", value);
			}
		}
		
		[MonoMac.Foundation.Connect("Btn17")]
		private global::MonoMac.AppKit.NSButton Btn17 {
			get {
				this.__mt_Btn17 = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("Btn17")));
				return this.__mt_Btn17;
			}
			set {
				this.__mt_Btn17 = value;
				this.SetNativeField("Btn17", value);
			}
		}
		
		[MonoMac.Foundation.Connect("TxtView")]
		private global::MonoMac.AppKit.NSTextView TxtView {
			get {
				this.__mt_TxtView = ((global::MonoMac.AppKit.NSTextView)(this.GetNativeField("TxtView")));
				return this.__mt_TxtView;
			}
			set {
				this.__mt_TxtView = value;
				this.SetNativeField("TxtView", value);
			}
		}
	}
}
