// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using System.IO;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Funny_Amazon_Reviews
{
	public partial class AboutViewCtrl : UIViewController
	{
		public AboutViewCtrl (IntPtr handle) : base (handle)
		{
		}

    public override void ViewDidLoad()
    {
      base.ViewDidLoad();

      string fileName = "About_iOS/about.html"; // remember case-sensitive
      string localHtmlUrl = Path.Combine (NSBundle.MainBundle.BundlePath, fileName);
      mAboutScreen.LoadRequest(new NSUrlRequest(new NSUrl(localHtmlUrl, false)));
    }
	}
}
