// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace asciiART
{
	public partial class AboutViewController : UIViewController
	{
		public AboutViewController (IntPtr handle) : base (handle)
		{
		}

    public override void ViewDidLoad()
    {
      base.ViewDidLoad();
      
      var url = NSUrl.FromFilename(@"copyright.html");
      var urlReq = new NSUrlRequest(url);
      mAboutWebView.LoadRequest(urlReq);
    }
	}
}
