// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Trek {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		private MonoTouch.UIKit.UIWindow __mt_window;
		
		private TrekViewController __mt_navigationController;
		
		private MonoTouch.UIKit.UITextField __mt_TxtGameSlot;
		
		private MonoTouch.UIKit.UIButton __mt_CmdAbout;
		
		private MonoTouch.UIKit.UIButton __mt_CmdHelp;
		
		private MonoTouch.UIKit.UIButton __mt_CmdLoadGame;
		
		private MonoTouch.UIKit.UIButton __mt_CmdResign;
		
		private MonoTouch.UIKit.UIButton __mt_CmdSaveGame;
		
		private MonoTouch.UIKit.UIButton __mt_CmdNavCalc;
		
		private MonoTouch.UIKit.UIButton __mt_CmdWarpEngineCtrl;
		
		private MonoTouch.UIKit.UITextField __mt_TxtNavCalcX;
		
		private MonoTouch.UIKit.UITextField __mt_TxtNavCalcY;
		
		private MonoTouch.UIKit.UIButton __mt_CmdStarBaseCalc;
		
		private MonoTouch.UIKit.UIButton __mt_CmdPhaserCtrl;
		
		private MonoTouch.UIKit.UIButton __mt_CmdPhotonTorpCalc;
		
		private MonoTouch.UIKit.UIButton __mt_CmdPhotonTorpCtrl;
		
		private MonoTouch.UIKit.UIButton __mt_CmdRepairDamage;
		
		private MonoTouch.UIKit.UIButton __mt_CmdShieldsEnergyAdd;
		
		private MonoTouch.UIKit.UIButton __mt_CmdShieldsEnergySubtract;
		
		private MonoTouch.UIKit.UITextField __mt_TxtPhotonTorpDirn;
		
		private MonoTouch.UIKit.UITextField __mt_TxtShieldsEnergyAmt;
		
		private MonoTouch.UIKit.UITextField __mt_TxtWarpEngineDirn;
		
		private MonoTouch.UIKit.UIButton __mt_CmdGalacticRecord;
		
		private MonoTouch.UIKit.UIButton __mt_CmdLongRangeScan;
		
		private MonoTouch.UIKit.UIButton __mt_CmdShortRangeScan;
		
		private MonoTouch.UIKit.UIButton __mt_CmdStatusReport;
		
		private MonoTouch.UIKit.UISwitch __mt_ChkAutoRepairDamage;
		
		private MonoTouch.UIKit.UITextField __mt_TxtWarpEngineDist;
		
		private MonoTouch.UIKit.UITextField __mt_TxtPhaserAmt;
		
		private TrekTextView __mt_TxtMain;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("OnExecuteCommand:")]
		partial void OnExecuteCommand (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Export("DidEndOnExit:")]
		partial void DidEndOnExit (MonoTouch.UIKit.UITextField sender);

		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("navigationController")]
		private TrekViewController navigationController {
			get {
				this.__mt_navigationController = ((TrekViewController)(this.GetNativeField("navigationController")));
				return this.__mt_navigationController;
			}
			set {
				this.__mt_navigationController = value;
				this.SetNativeField("navigationController", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("TxtGameSlot")]
		private MonoTouch.UIKit.UITextField TxtGameSlot {
			get {
				this.__mt_TxtGameSlot = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("TxtGameSlot")));
				return this.__mt_TxtGameSlot;
			}
			set {
				this.__mt_TxtGameSlot = value;
				this.SetNativeField("TxtGameSlot", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdAbout")]
		private MonoTouch.UIKit.UIButton CmdAbout {
			get {
				this.__mt_CmdAbout = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdAbout")));
				return this.__mt_CmdAbout;
			}
			set {
				this.__mt_CmdAbout = value;
				this.SetNativeField("CmdAbout", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdHelp")]
		private MonoTouch.UIKit.UIButton CmdHelp {
			get {
				this.__mt_CmdHelp = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdHelp")));
				return this.__mt_CmdHelp;
			}
			set {
				this.__mt_CmdHelp = value;
				this.SetNativeField("CmdHelp", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdLoadGame")]
		private MonoTouch.UIKit.UIButton CmdLoadGame {
			get {
				this.__mt_CmdLoadGame = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdLoadGame")));
				return this.__mt_CmdLoadGame;
			}
			set {
				this.__mt_CmdLoadGame = value;
				this.SetNativeField("CmdLoadGame", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdResign")]
		private MonoTouch.UIKit.UIButton CmdResign {
			get {
				this.__mt_CmdResign = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdResign")));
				return this.__mt_CmdResign;
			}
			set {
				this.__mt_CmdResign = value;
				this.SetNativeField("CmdResign", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdSaveGame")]
		private MonoTouch.UIKit.UIButton CmdSaveGame {
			get {
				this.__mt_CmdSaveGame = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdSaveGame")));
				return this.__mt_CmdSaveGame;
			}
			set {
				this.__mt_CmdSaveGame = value;
				this.SetNativeField("CmdSaveGame", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdNavCalc")]
		private MonoTouch.UIKit.UIButton CmdNavCalc {
			get {
				this.__mt_CmdNavCalc = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdNavCalc")));
				return this.__mt_CmdNavCalc;
			}
			set {
				this.__mt_CmdNavCalc = value;
				this.SetNativeField("CmdNavCalc", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdWarpEngineCtrl")]
		private MonoTouch.UIKit.UIButton CmdWarpEngineCtrl {
			get {
				this.__mt_CmdWarpEngineCtrl = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdWarpEngineCtrl")));
				return this.__mt_CmdWarpEngineCtrl;
			}
			set {
				this.__mt_CmdWarpEngineCtrl = value;
				this.SetNativeField("CmdWarpEngineCtrl", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("TxtNavCalcX")]
		private MonoTouch.UIKit.UITextField TxtNavCalcX {
			get {
				this.__mt_TxtNavCalcX = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("TxtNavCalcX")));
				return this.__mt_TxtNavCalcX;
			}
			set {
				this.__mt_TxtNavCalcX = value;
				this.SetNativeField("TxtNavCalcX", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("TxtNavCalcY")]
		private MonoTouch.UIKit.UITextField TxtNavCalcY {
			get {
				this.__mt_TxtNavCalcY = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("TxtNavCalcY")));
				return this.__mt_TxtNavCalcY;
			}
			set {
				this.__mt_TxtNavCalcY = value;
				this.SetNativeField("TxtNavCalcY", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdStarBaseCalc")]
		private MonoTouch.UIKit.UIButton CmdStarBaseCalc {
			get {
				this.__mt_CmdStarBaseCalc = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdStarBaseCalc")));
				return this.__mt_CmdStarBaseCalc;
			}
			set {
				this.__mt_CmdStarBaseCalc = value;
				this.SetNativeField("CmdStarBaseCalc", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdPhaserCtrl")]
		private MonoTouch.UIKit.UIButton CmdPhaserCtrl {
			get {
				this.__mt_CmdPhaserCtrl = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdPhaserCtrl")));
				return this.__mt_CmdPhaserCtrl;
			}
			set {
				this.__mt_CmdPhaserCtrl = value;
				this.SetNativeField("CmdPhaserCtrl", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdPhotonTorpCalc")]
		private MonoTouch.UIKit.UIButton CmdPhotonTorpCalc {
			get {
				this.__mt_CmdPhotonTorpCalc = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdPhotonTorpCalc")));
				return this.__mt_CmdPhotonTorpCalc;
			}
			set {
				this.__mt_CmdPhotonTorpCalc = value;
				this.SetNativeField("CmdPhotonTorpCalc", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdPhotonTorpCtrl")]
		private MonoTouch.UIKit.UIButton CmdPhotonTorpCtrl {
			get {
				this.__mt_CmdPhotonTorpCtrl = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdPhotonTorpCtrl")));
				return this.__mt_CmdPhotonTorpCtrl;
			}
			set {
				this.__mt_CmdPhotonTorpCtrl = value;
				this.SetNativeField("CmdPhotonTorpCtrl", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdRepairDamage")]
		private MonoTouch.UIKit.UIButton CmdRepairDamage {
			get {
				this.__mt_CmdRepairDamage = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdRepairDamage")));
				return this.__mt_CmdRepairDamage;
			}
			set {
				this.__mt_CmdRepairDamage = value;
				this.SetNativeField("CmdRepairDamage", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdShieldsEnergyAdd")]
		private MonoTouch.UIKit.UIButton CmdShieldsEnergyAdd {
			get {
				this.__mt_CmdShieldsEnergyAdd = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdShieldsEnergyAdd")));
				return this.__mt_CmdShieldsEnergyAdd;
			}
			set {
				this.__mt_CmdShieldsEnergyAdd = value;
				this.SetNativeField("CmdShieldsEnergyAdd", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdShieldsEnergySubtract")]
		private MonoTouch.UIKit.UIButton CmdShieldsEnergySubtract {
			get {
				this.__mt_CmdShieldsEnergySubtract = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdShieldsEnergySubtract")));
				return this.__mt_CmdShieldsEnergySubtract;
			}
			set {
				this.__mt_CmdShieldsEnergySubtract = value;
				this.SetNativeField("CmdShieldsEnergySubtract", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("TxtPhotonTorpDirn")]
		private MonoTouch.UIKit.UITextField TxtPhotonTorpDirn {
			get {
				this.__mt_TxtPhotonTorpDirn = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("TxtPhotonTorpDirn")));
				return this.__mt_TxtPhotonTorpDirn;
			}
			set {
				this.__mt_TxtPhotonTorpDirn = value;
				this.SetNativeField("TxtPhotonTorpDirn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("TxtShieldsEnergyAmt")]
		private MonoTouch.UIKit.UITextField TxtShieldsEnergyAmt {
			get {
				this.__mt_TxtShieldsEnergyAmt = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("TxtShieldsEnergyAmt")));
				return this.__mt_TxtShieldsEnergyAmt;
			}
			set {
				this.__mt_TxtShieldsEnergyAmt = value;
				this.SetNativeField("TxtShieldsEnergyAmt", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("TxtWarpEngineDirn")]
		private MonoTouch.UIKit.UITextField TxtWarpEngineDirn {
			get {
				this.__mt_TxtWarpEngineDirn = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("TxtWarpEngineDirn")));
				return this.__mt_TxtWarpEngineDirn;
			}
			set {
				this.__mt_TxtWarpEngineDirn = value;
				this.SetNativeField("TxtWarpEngineDirn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdGalacticRecord")]
		private MonoTouch.UIKit.UIButton CmdGalacticRecord {
			get {
				this.__mt_CmdGalacticRecord = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdGalacticRecord")));
				return this.__mt_CmdGalacticRecord;
			}
			set {
				this.__mt_CmdGalacticRecord = value;
				this.SetNativeField("CmdGalacticRecord", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdLongRangeScan")]
		private MonoTouch.UIKit.UIButton CmdLongRangeScan {
			get {
				this.__mt_CmdLongRangeScan = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdLongRangeScan")));
				return this.__mt_CmdLongRangeScan;
			}
			set {
				this.__mt_CmdLongRangeScan = value;
				this.SetNativeField("CmdLongRangeScan", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdShortRangeScan")]
		private MonoTouch.UIKit.UIButton CmdShortRangeScan {
			get {
				this.__mt_CmdShortRangeScan = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdShortRangeScan")));
				return this.__mt_CmdShortRangeScan;
			}
			set {
				this.__mt_CmdShortRangeScan = value;
				this.SetNativeField("CmdShortRangeScan", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CmdStatusReport")]
		private MonoTouch.UIKit.UIButton CmdStatusReport {
			get {
				this.__mt_CmdStatusReport = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CmdStatusReport")));
				return this.__mt_CmdStatusReport;
			}
			set {
				this.__mt_CmdStatusReport = value;
				this.SetNativeField("CmdStatusReport", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("ChkAutoRepairDamage")]
		private MonoTouch.UIKit.UISwitch ChkAutoRepairDamage {
			get {
				this.__mt_ChkAutoRepairDamage = ((MonoTouch.UIKit.UISwitch)(this.GetNativeField("ChkAutoRepairDamage")));
				return this.__mt_ChkAutoRepairDamage;
			}
			set {
				this.__mt_ChkAutoRepairDamage = value;
				this.SetNativeField("ChkAutoRepairDamage", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("TxtWarpEngineDist")]
		private MonoTouch.UIKit.UITextField TxtWarpEngineDist {
			get {
				this.__mt_TxtWarpEngineDist = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("TxtWarpEngineDist")));
				return this.__mt_TxtWarpEngineDist;
			}
			set {
				this.__mt_TxtWarpEngineDist = value;
				this.SetNativeField("TxtWarpEngineDist", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("TxtPhaserAmt")]
		private MonoTouch.UIKit.UITextField TxtPhaserAmt {
			get {
				this.__mt_TxtPhaserAmt = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("TxtPhaserAmt")));
				return this.__mt_TxtPhaserAmt;
			}
			set {
				this.__mt_TxtPhaserAmt = value;
				this.SetNativeField("TxtPhaserAmt", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("TxtMain")]
		private TrekTextView TxtMain {
			get {
				this.__mt_TxtMain = ((TrekTextView)(this.GetNativeField("TxtMain")));
				return this.__mt_TxtMain;
			}
			set {
				this.__mt_TxtMain = value;
				this.SetNativeField("TxtMain", value);
			}
		}
	}
	
	// Base type probably should be MonoTouch.UIKit.UITabBarController or subclass
	[MonoTouch.Foundation.Register("TrekViewController")]
	public partial class TrekViewController {
	}
	
	// Base type probably should be MonoTouch.UIKit.UITextView or subclass
	[MonoTouch.Foundation.Register("TrekTextView")]
	public partial class TrekTextView {
	}
}
